version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: ./.docker/app/Dockerfile
    environment:
      - HOST=0.0.0.0
      - LANG=C.UTF-8
      - EDITOR=vim
    ports:
      - "${PUMA_PORT:-9292}:9292"
    tty: true
    volumes:
      - .:/myapp:cached
      - bundle:/usr/local/bundle
    working_dir: /myapp
    depends_on:
      - db

  db:
    image: mysql:5.7.24
    command: --character-set-server=utf8mb4
    environment:
      - LANG=C.UTF-8
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=myapp
    ports:
      - "${EXTERNAL_MYSQL_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  bundle:
